name: JS Lint

on: 'push'

jobs:
  js-lint:
    name: Lint source code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.1'

    - name: Install dependencies
      run: |
        npm install

    - name: Lint files
      run: |
        npm run wp:lint-js